/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Surfaces
        'background':                '#0c1324',
        'surface':                   '#0c1324',
        'surface-dim':               '#0c1324',
        'surface-bright':            '#33394c',
        'surface-container-lowest':  '#070d1f',
        'surface-container-low':     '#151b2d',
        'surface-container':         '#191f31',
        'surface-container-high':    '#23293c',
        'surface-container-highest': '#2e3447',
        'surface-variant':           '#2e3447',
        'surface-tint':              '#ffb690',
        // On-surface
        'on-background':      '#dce1fb',
        'on-surface':         '#dce1fb',
        'on-surface-variant': '#e0c0b1',
        'inverse-surface':    '#dce1fb',
        'inverse-on-surface': '#2a3043',
        // Outline
        'outline':         '#a78b7d',
        'outline-variant': '#584237',
        // Primary (sunset orange)
        'primary':             '#ffb690',
        'on-primary':          '#552100',
        'primary-container':   '#f97316',
        'on-primary-container':'#582200',
        'primary-fixed':       '#ffdbca',
        'primary-fixed-dim':   '#ffb690',
        'on-primary-fixed':    '#341100',
        'on-primary-fixed-variant': '#783200',
        'inverse-primary':     '#9d4300',
        // Secondary (indigo)
        'secondary':             '#c0c1ff',
        'on-secondary':          '#1000a9',
        'secondary-container':   '#3131c0',
        'on-secondary-container':'#b0b2ff',
        'secondary-fixed':       '#e1e0ff',
        'secondary-fixed-dim':   '#c0c1ff',
        'on-secondary-fixed':    '#07006c',
        'on-secondary-fixed-variant': '#2f2ebe',
        // Tertiary (sky blue)
        'tertiary':             '#93ccff',
        'on-tertiary':          '#003351',
        'tertiary-container':   '#00a2f4',
        'on-tertiary-container':'#003554',
        'tertiary-fixed':       '#cde5ff',
        'tertiary-fixed-dim':   '#93ccff',
        'on-tertiary-fixed':    '#001d32',
        'on-tertiary-fixed-variant': '#004b74',
        // Error
        'error':             '#ffb4ab',
        'on-error':          '#690005',
        'error-container':   '#93000a',
        'on-error-container':'#ffdad6',
        // Training phase semantics
        'phase-foundation': '#94A3B8',
        'phase-aerobic':    '#38BDF8',
        'phase-build':      '#F97316',
        'phase-taper':      '#A855F7',
        // Status
        'success-green': '#22C55E',
        // Base slates (used for deep backgrounds)
        'slate-950': '#020617',
        'slate-900': '#0F172A',
        'slate-50':  '#F8FAFC',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'ui-monospace', 'monospace'],
        'label-mono':       ['JetBrains Mono', 'monospace'],
        'display-lg':       ['Inter', 'sans-serif'],
        'display-lg-mobile':['Inter', 'sans-serif'],
        'headline-lg':      ['Inter', 'sans-serif'],
        'headline-md':      ['Inter', 'sans-serif'],
        'body-lg':          ['Inter', 'sans-serif'],
        'body-md':          ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg':        ['64px',  { lineHeight: '72px',  letterSpacing: '-0.04em', fontWeight: '800' }],
        'display-lg-mobile': ['40px',  { lineHeight: '44px',  letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg':       ['32px',  { lineHeight: '40px',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md':       ['24px',  { lineHeight: '32px',  fontWeight: '600' }],
        'body-lg':           ['18px',  { lineHeight: '28px',  fontWeight: '400' }],
        'body-md':           ['16px',  { lineHeight: '24px',  fontWeight: '400' }],
        'label-mono':        ['12px',  { lineHeight: '16px',  letterSpacing: '0.05em', fontWeight: '500' }],
      },
      spacing: {
        'container-max':  '1280px',
        'gutter':         '24px',
        'margin-desktop': '64px',
        'margin-mobile':  '20px',
        'stack-unit':     '8px',
      },
      borderRadius: {
        'sm':      '0.25rem',
        DEFAULT:   '0.5rem',
        'md':      '0.75rem',
        'lg':      '1rem',
        'xl':      '1.5rem',
        '2xl':     '1.5rem',
        '3xl':     '2rem',
        'full':    '9999px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
